title: "Leibniz Blog"
lang: pt-BR

url: "https://carloscostamath.github.io"  # Corrigido espaço extra
baseurl: "/leibniz"          # "" se for user site
timezone: America/Maceio
future: true

markdown: kramdown
theme: null
permalink: /:year/:month/:day/:title/

collections:
  posts:
    output: true

excerpt_separator: "<!--more-->"
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-read-time # <-- Adicionado este plugin

paginate: 7
paginate_path: "/page/:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      extra_css:
        - /assets/css/post.css

# Configuração opcional para o plugin jekyll-read-time
# Consulte a documentação do plugin para mais opções
# read_time:
#   words_per_minute: 200  # Valor padrão, pode ser alterado se desejar
