title: "Leibniz Blog"
lang: pt-BR

url: "https://carloscostamath.github.io"
baseurl: "/leibniz"          # "" se for user site
timezone: America/Maceio
future: true

markdown: kramdown
theme: null
permalink: /:categories/:year/:month/:day/:title/

collections:
  posts:
    output: true

excerpt_separator: "<!--more-->"
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: taxonomy_archive
  permalinks:
    category: /categoria/:name/
    tag: /tag/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      extra_css:
        - /assets/css/post.css
